"""initial_migration

Revision ID: 21ba42f81c2b
Revises: 
Create Date: 2026-07-28 10:34:31.929397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ba42f81c2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('subscription_tier', sa.String(length=32), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('autoclose_enabled', sa.Boolean(), nullable=False),
    sa.Column('autoclose_rules', sa.JSON(), nullable=True),
    sa.Column('subscription_reminder_state', sa.JSON(), nullable=True),
    sa.Column('groups', sa.JSON(), nullable=True),
    sa.Column('admins', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('presence_polls',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('here_tg_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', 'message_id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_name', sa.String(length=512), nullable=False),
    sa.Column('kings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'subject_name', name='uq_chat_subject_name')
    )
    op.create_index(op.f('ix_subject_chat_id'), 'subject', ['chat_id'], unique=False)
    op.create_index(op.f('ix_subject_id'), 'subject', ['id'], unique=False)
    op.create_table('users',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=255), nullable=True),
    sa.Column('real_name', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('yookassa_payment_id', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('amount_rub', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yookassa_payment_id')
    )
    op.create_table('queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('lesson_date', sa.DateTime(), nullable=False),
    sa.Column('close_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'chat_id', 'lesson_date', name='unique_subject_chat_lesson')
    )
    op.create_index(op.f('ix_queue_chat_id'), 'queue', ['chat_id'], unique=False)
    op.create_table('queue_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('history_position', sa.JSON(), nullable=False),
    sa.Column('missed_attempts_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id', 'subject_id', name='uq_history_user_subject')
    )
    op.create_table('swap_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('queue_message_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('from_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('to_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('swap_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swap_requests_chat_id'), 'swap_requests', ['chat_id'], unique=False)
    op.create_index(op.f('ix_swap_requests_queue_message_id'), 'swap_requests', ['queue_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swap_requests_queue_message_id'), table_name='swap_requests')
    op.drop_index(op.f('ix_swap_requests_chat_id'), table_name='swap_requests')
    op.drop_table('swap_requests')
    op.drop_table('queue_history')
    op.drop_index(op.f('ix_queue_chat_id'), table_name='queue')
    op.drop_table('queue')
    op.drop_table('payments')
    op.drop_table('users')
    op.drop_index(op.f('ix_subject_id'), table_name='subject')
    op.drop_index(op.f('ix_subject_chat_id'), table_name='subject')
    op.drop_table('subject')
    op.drop_table('presence_polls')
    op.drop_table('chats')
    # ### end Alembic commands ###
